spring:
  config:
    import: ${ENV_CLOUD_CONFIG_SERVER:optional:configserver:http://localhost:8001}
  cloud:
    config:
      name: api-microservices-eureka
      profile: ${ENV_CLOUD_CONFIG_PROFILE:default}
      label: ${ENV_CLOUD_CONFIG_LABEL:master}
